/***********************************************************************
* Program:
*    Test 2, Guessing Game          (e.g. Test 2, Flip a coin)  
*    Brother Christensen, CS124
* Author:
*    Brendon Marques
* Summary: 
*    This program is a guessing game. It prompts the user for a number,
*    then, it tells the user if the number is too high or too low than
*    the number generated by the program. Once you get it right, the
*    program will display how many times you tried to guess.
*
************************************************************************/

#include <iostream>   // for CIN, COUT
#include <ctime>      // for time(), part of the random process
#include <stdlib.h>   // for rand() and srand()
using namespace std;

// prototypes
int promptNumber();
void display(int count);
void displayHigh();
void displayLow();

/**********************************************************************
 * main
 *
 * The main function is responsible for starting the program and calling
 * the other functions.
 ***********************************************************************/
int main(int argc, char **argv)
{
   
   // this code is necessary to set up the random number generator. If
   // your program uses a random number generator, you will need this 
   // code. Otherwise, you can safely delete it.  Note: this must go in main()
   srand(argc == 1 ? time(NULL) : (int)argv[1][1]);

   // this code will actually generate a random number between 0 and 999
   int number = rand() % 100;

   // variables
   int count = 0;
   int guess;
   
   // do-while loop to keep asking for a number until the number is correct
   do
   {
      guess = promptNumber();
  
      // this variable keeps a track of how many guesses
      count++;

      if (guess > number)

         displayHigh();

      else if (guess < number)

         displayLow();
      
   }
   while (guess != number);

   // display function will display to the user 
   // how many times he or she guessed
   display(count);      
      
   return 0;
   
}

/**********************************************************************
 * promptNumber
 *
 * This function will prompt the user for a number
 ***********************************************************************/
int promptNumber()
{
   int guess;
   cout << "What is your guess: ";
   cin >> guess;

   return guess;
}

/**********************************************************************
 * displayHigh
 *
 * This function will be executed when the guess is too high
 ***********************************************************************/
void displayHigh()
{
   cout << "Too high\n";
}

/**********************************************************************
 * displayLow
 *
 * This function will be executed when the guess is too low
 ***********************************************************************/
void displayLow()
{
   cout << "Too low\n";
}

/**********************************************************************
 * display
 *
 * This function will be executed when the guess is correct, displaying
 * the number of guesses
 ***********************************************************************/
void display(int count)
{
   cout << "You guessed it in " << count << " tries\n";
}
